initfs patches

diff --git a/aports/main/postmarketos-mkinitfs/init.sh.in b/aports/main/postmarketos-mkinitfs/init.sh.in
--- a/aports/main/postmarketos-mkinitfs/init.sh.in
+++ b/aports/main/postmarketos-mkinitfs/init.sh.in
@@ -13,7 +13,11 @@ setup_log
 # shellcheck disable=SC2154,SC2086
 [ -d /lib/modules ] && modprobe -a ${deviceinfo_modules_initfs} ext4
 setup_mdev
-mount_subpartitions
+if ! mount_subpartitions; then
+	echo "mount_subpartitions failed; waiting and trying again"
+	sleep 1
+	mount_subpartitions
+fi
 
 # Start msm-fb-refresher workaround for qualcomm devices
 start_msm_refresher
